name: Submit Suggestion
description: If you have any suggestions for the downloader, you can submit them here.
labels: ["enhancement"]
body:
  - type: dropdown
    id: "yml-0"
    attributes:
      label: "Downloader Information"
      description: "Please select the downloader for which you would like to submit a suggestion"
      options:
        - Suya Downloader
        - Easy Language Version Downloader
      default: 0
  - type: checkboxes
    id: "yml-1"
    attributes:
      label: "Checklist"
      description: "Please check the following items one by one and tick them to confirm."
      options:
        - label: "I confirm that this issue has not been addressed in the latest version of the downloader"
          required: true
        - label: "I confirm that there are no other identical suggestions in Issues"
          required: true
        - label: "If you have tried the latest dev version of the code, the issue still persists in the latest dev version"
    # 注意：这个选项的描述可能有些不完整或不清楚，我假设它的意思是“如果你尝试过最新的开发版本代码，但问题在最新的开发版本中仍然存在”
  - type: textarea
    id: "yml-2"
    attributes:
      label: Desired Feature
      placeholder: "- (Please answer here) -"
      validations:
        required: true
  - type: textarea
    id: "yml-3"
    attributes:
      label: Downloader Version You Are Using
      placeholder: "- (Please answer here) -"
  - type: textarea
    id: "yml-4"
    attributes:
      label: Other Supplementary Information
      placeholder: "- (Please answer here) -"